name: r2u

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: rocker/r2u:latest

    steps:
      - uses: actions/checkout@v5

      - name: SessionInfo
        shell: Rscript {0}
        run: sessionInfo()

      - name: System Dependencies
        # can be used to install e.g. cmake or other build dependencies
        run: apt update -qq && apt install --yes --no-install-recommends pandoc

      #- name: Package Dependencies
      #  shell: Rscript {0}
      #  run: remotes::install_deps(".", dependencies=TRUE)

      #- name: Build Package
      #  run: R CMD build --no-build-vignettes --no-manual .

      #- name: Check Package
      #  run: R CMD check --no-vignettes --no-manual $(ls -1tr *.tar.gz | tail -1)

      - name: Install ctv Package Dependencies
        shell: Rscript {0}
        run: install.packages(c("ctv", "knitr", "rmarkdown"))

      - name: Set File Name
        shell: Rscript {0}
        run: |
          md <- paste0(basename(getwd()), ".md")
          if (!file.exists(md)) md <- setdiff(Sys.glob("*.md"), "README.md")
          if (length(md) > 1L) md <- md[1L]
          cat(paste0("MD=", md, "\n"), file=Sys.getenv("GITHUB_ENV"), append=TRUE)

      - name: Run an existence test for main .md file
        shell: Rscript {0}
        run: |
          ok <- file.exists(Sys.getenv("MD"))
          # TRUE is success and returned as zero
          q("no", status = as.integer(!ok))  
          
      - name: Convert ctv File from md to html
        shell: Rscript {0}
        run: ctv::ctv2html(Sys.getenv("MD"))

      - name: Run package check on
        shell: Rscript {0}
        run: |
          res <- ctv::check_ctv_packages(Sys.getenv("MD"))
          res <- Filter(length, res)
          str(res)
          # Zero packages to adjust is success; zero is shell success
          # Any non-zero number is failure and 'work to do'
          q("no", status = as.integer(sum(lengths(res))))  
          
